# Generated by Django 3.2.9 on 2021-11-24 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profiles_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=10),
        ),
    ]
