# Generated by Django 3.2.9 on 2021-11-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0011_profiles_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='topic-title', max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('date_created', models.DateTimeField(default='2021-11-24 01:23:31', null=True)),
                ('postedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posteduser', to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentTitle', models.CharField(default='topic-title', max_length=200)),
                ('comments', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(default='2021-11-24 01:23:31', null=True)),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentuser', to='profiles.profiles')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forums.posts')),
            ],
        ),
    ]
