# Generated by Django 3.2.9 on 2021-11-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='commentUser',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='date_created',
            field=models.DateTimeField(default='2021-11-24 14:12:17', null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default='2021-11-24 14:12:17', null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postedUser',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
