# Generated by Django 3.2.9 on 2021-11-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20211124_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='date_created',
            field=models.DateTimeField(default='2021-11-24 16:14:15', null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default='2021-11-24 16:14:15', null=True),
        ),
    ]
