# Generated by Django 3.2.9 on 2021-11-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20211124_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='date_created',
            field=models.DateTimeField(default='2021-11-24 19:30:41', null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default='2021-11-24 19:30:41', null=True),
        ),
    ]
