# Generated by Django 3.2.9 on 2021-11-25 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_auto_20211125_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 11, 56, 34), null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 11, 56, 34), null=True),
        ),
    ]
